{
 "title": "Financial",
 "time": { "from": "now - 2y", "to": "now" },
 "panels": [
  { "title": "Expense", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Electricity fee",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyVND" } },
   "targets": [
    {
     "query": "from(bucket: \"financial\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Main Bank\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> filter(fn: (r) => r[\"group\"] == \"Điện\")"
    }
   ]
  },
  {
   "title": "Water fee",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyVND" } },
   "targets": [
    {
     "query": "from(bucket: \"financial\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Main Bank\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> filter(fn: (r) => r[\"group\"] == \"Nước\")"
    }
   ]
  },
  {
   "title": "Top 5 expenses each month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyVND" } },
   "targets": [
    {
     "query": "from(bucket: \"financial\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"type\"] == \"EXPENSE\")\n  |> filter(fn: (r) => r[\"group\"] != \"Rút tiền\")\n  |> filter(fn: (r) => r[\"group\"] != \"Cho vay\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> group()\n  |> window(every: 1mo)\n  |> sort(desc: true)\n  |> limit(n: 5)\n  |> group(columns: [\"group\"])"
    }
   ]
  },
  {
   "title": "Income",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Salary",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "currencyVND" } },
     "targets": [
      {
       "query": "from(bucket: \"financial\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Main Bank\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> filter(fn: (r) => r[\"group\"] == \"Lương\")"
      }
     ]
    },
    {
     "title": "Total income",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "currencyVND" } },
     "targets": [
      {
       "query": "from(bucket: \"financial\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Main Bank\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> filter(fn: (r) => r[\"type\"] == \"INCOME\")\n  |> filter(fn: (r) => r[\"group\"] != \"Đi vay\")\n  |> filter(fn: (r) => r[\"group\"] != \"Thu nợ\")\n  |> group(columns: [\"type\"])\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Income detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "currencyVND" } },
     "targets": [
      {
       "query": "from(bucket: \"financial\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Main Bank\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amount\")\n  |> filter(fn: (r) => r[\"type\"] == \"INCOME\")\n  |> filter(fn: (r) => r[\"group\"] != \"Đi vay\")\n  |> filter(fn: (r) => r[\"group\"] != \"Thu nợ\")"
      }
     ]
    }
   ]
  }
 ]
}